### ISSUE TITLE
Rails `BulkAlterTableMigrationsTest#test_default_functions_on_columns` fails against trilogy and MariaDB

### ISSUE THREAD

**Issue by yahonda** [trilogy-libraries/trilogy#96]
One of Rails unit test`BulkAlterTableMigrationsTest#test_default_functions_on_columns` fails against trilogy and MariaDB. 

### Steps to reproduce

1. Install MariaDB

```sql
MariaDB [test]> select version();
+----------------+
| version()      |
+----------------+
| 11.1.1-MariaDB |
+----------------+
1 row in set (0.000 sec)
```

2. Run Active Record unit test 

```ruby
git clone https://github.com/rails/rails
cd rails/activerecord
bundle install
ARCONN=trilogy bin/test test/cases/migration_test.rb -n test_default_functions_on_columns
```

### Expected behavior
It should pass.

### Actual behavior

```ruby
$ ARCONN=trilogy bin/test test/cases/migration_test.rb -n test_default_functions_on_columns
Using trilogy
Run options: -n test_default_functions_on_columns --seed 54410

# Running:

E

Error:
BulkAlterTableMigrationsTest#test_default_functions_on_columns:
ArgumentError: wrong number of arguments (given 1, expected 0)
    /home/yahonda/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/trilogy-8e4ae98569c1/contrib/ruby/lib/trilogy.rb:233:in `each'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/migration_test.rb:1472:in `to_a'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/migration_test.rb:1472:in `test_default_functions_on_columns'


bin/test test/cases/migration_test.rb:1454



Finished in 0.208410s, 4.7982 runs/s, 9.5965 assertions/s.
1 runs, 2 assertions, 0 failures, 1 errors, 0 skips
$
```

**Comment by yahonda** [comment]
It only gets error only if MariaDB and trilogy is used.

- MariaDB that `supports_text_column_with_default?` returns true
https://github.com/rails/rails/blob/d867313fbc237672feb1d1cb3ae3eb3d683d4c16/activerecord/test/support/adapter_helper.rb#L38-L45

```ruby
  def supports_text_column_with_default?
    if current_adapter?(:Mysql2Adapter, :TrilogyAdapter)
      conn = ActiveRecord::Base.connection
      conn.mariadb? && conn.database_version >= "10.2.1"
    else
      true
    end
  end
```

**Comment by yahonda** [comment]
Looks like this is an expected behavior. 

https://github.com/rails/rails/commit/191ae490ed54744156e4c0233bdcd779beca921b says
> * to_a(as: :hash) is not supported on trilogy. And we should be dealing
with ActiveRecord::Result objects anyway.
